# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'Live' do
pod 'SVProgressHUD'
pod 'TextAttributes'
pod 'R.swift'
pod 'IHKeyboardAvoiding', '~> 2.6'
pod 'Socket.IO-Client-Swift', '~> 10.0'
pod 'LFLiveKit'
end
